version: "3"
services:
    nginx:
        build:
            context: site/docker/development/nginx
        ports:
            - "8080:80"
        volumes:
            - ./site:/app
        depends_on:
            - php-fpm
    php-fpm:
        build:
            context: site/docker/development/php-fpm
        volumes:
            - ./site:/app